### ISSUE TITLE
[Bug] Ctrl+Q is marked, but does not close Insomnia

### ISSUE THREAD

**Issue by stdedos** [getinsomnia/insomnia#1446]
- Insomnia Version: 6.4.0
Version 6.4.0
Shell 3.0.4
Node 10.2.0
V8 6.6.346.32
Architecture x64

libcurl/7.61.1 OpenSSL/1.1.0h zlib/1.2.11 nghttp2/1.29.0
- Operating System: Ubuntu 16.04.5

## Details

![Screenshot 2019-04-23 10:24:05](https://user-images.githubusercontent.com/133706/56562456-0e4ca980-65b2-11e9-94cc-46d3810c9ec7.png)

**Comment by gschier** [comment]
Ah, good catch. That hotkey should only be shown for Mac

**Comment by stdedos** [comment]
_I'd much rather you'd register it 😕_
Ctrl+Q / Ctrl+W / Alt+F,X ...

I could guess that Alt+F4 does the work, but, working on Ubuntu (Linux?), different layouts come to mind usually

**Comment by gschier** [comment]
I'm not sure what best practices on Windows/Linux are. Is Ctrl+w the most common? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by stdedos** [comment]
> I'm not sure what best practices on Windows/Linux are. Is Ctrl+w the most common?

From my experience, `Ctrl+Q` (as in Quit) is a common option (e.g. Sublime, VLC, Evolution, Libre Office, Chrome `Ctrl+Shift+Q` before moving to `Alt+F,X`)

`Ctrl+W` would be to close windows/tabs (if this is the case). In that case, `Ctrl+W` closing the last window, _could have `Quit` a side-effect (instead of closing the window, to start on a new "environment" next time, Chrome), or not (Firefox)_

**Comment by finex** [comment]
Hi, on my Insomnia version (6.5.3, Archlinux) the menu is different: it only contains "preferences" and "changelog" so I've to force quit the application using the window manager shortcut (in my case Awesome WM).

**Comment by stdedos** [comment]
@finex obviously it looks differently!

This is closed & resolved in https://github.com/getinsomnia/insomnia/commit/6f98da7df89fa0da646ad5950defd8c4c9bd8771
and in: v6.5.3  v6.5.1 v6.5.0 v6.4.2 v6.4.1

I was hoping that @gschier would also resolve the comment https://github.com/getinsomnia/insomnia/issues/1446#issuecomment-486107294 (which theoretically needs its own Issue), but probably not happening.

**Comment by johnjago** [comment]
I also use a window manager (dwm) like @finex does, and there is no way to quit the application using a standard shortcut, so I have to use the window manager manager shortcut. The behavior that @stdedos described is correct based on my experience with Linux. It's usually the same for Windows as well.

My Insomnia version is 6.5.4.

**Comment by stdedos** [comment]
Yes, as @johnjago mentions, it is like that as well on Windows (I probably missed that one).
The "windows manager" shortcut on Windows would be `Alt+F4`, but I don't think you need to cover this case - making `Ctrl+Q` work would be enough

**Comment by finex** [comment]
Hi, the issue is still reproducible on 7.0.3: I'm using Insomnia from Archlinux/AUR package. The desktop environment is AwesomeWM and there is no "quit/close" action on the menu... just like the old version :-)
