### ISSUE TITLE
Postman collection import successful, but not visible on any dashboard

### ISSUE THREAD

**Issue by jpuris** [getinsomnia/insomnia#4034]
### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for a bug that matches the one I want to file, without success.

### Insomnia Version

2021.5.2

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.5.2

### Installation method

homebrew

### Last Known Working Insomnia version

none

### Expected Behavior

Collection to show up on dashboard after successful import.

### Actual Behavior

No collection is visible or accessible anywhere in Insomnia.

### Reproduction Steps

1. Open Insomnia
2. Under create, choose IMPORT FROM => "URL"
3. Fill in
    ```
    https://fivetran.com/assets-docs/postman/rest_api_collection.json
    ```
4. Press Fetch and Import
5.  "Import Succeeded" message appears with "You imported 6 Folders, 35 Requests!"
6. PROBEM: No new collections..

### Additional Information

I've tried this with Paw and Postman, which imports the collection without issues.
Can also be reproduced with Insomnia native collection format https://git.io/github-v3-rest-api-for-insomnia

Exact steps in screenshots below
![CleanShot 2021-09-16 at 15 39 49@2x](https://user-images.githubusercontent.com/4112811/133633442-bf116460-d542-4e0d-86da-b5d95a1875ff.png)
![CleanShot 2021-09-16 at 15 39 53@2x](https://user-images.githubusercontent.com/4112811/133633451-4ea3ff2d-42e3-4429-a2ff-536ad094d779.png)
![CleanShot 2021-09-16 at 15 39 58@2x](https://user-images.githubusercontent.com/4112811/133633464-c827eeeb-a02b-41bc-8b15-f786e02ada50.png)
![CleanShot 2021-09-16 at 15 40 03@2x](https://user-images.githubusercontent.com/4112811/133633471-c1f7bdb1-9439-47cf-8331-491f2d36e934.png)

**Comment by degueba** [comment]
I'm having the same issue here.

**Comment by Jaakkonen** [comment]
Happens with HAR import too on Insomnia versions
- 2021.5.3
- 2021.4.1
- 2021.3.0
- 2021.2.2
- 2021.1.1
running on Arch Linux. 

The old UI flow still works though. Create a request collection, go to it, click it's name in the top bar, click "Import/Export" and import requests from there.

**Comment by blshkv** [comment]
There is actually an error if you try to import it from cli:
![Screenshot_20210922_083728](https://user-images.githubusercontent.com/309751/134265713-9ac80cb6-fd3a-4b59-b57c-cc9f0b71f1ec.png)

Could be something to do with a scheme?
"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"

**Comment by develohpanda** [comment]
Thanks for reporting this! We've seen a number of reports for the Postman import failing in this way. This is on our sprint and should be fixed with the upcoming major release (likely towards the end of October). 🙌🏽 

In the meantime, as a workaround, you can create a Request Collection as normal, then open that collection, and select the import option.

![image](https://user-images.githubusercontent.com/4312346/134453359-0658a91a-77bd-4446-a151-9cd872305105.png)

Once you import from a file or url from within a collection, Insomnia will prompt you with a prompt, and from there choose to import into the "current workspace".

**Comment by blshkv** [comment]
Wow, that's tricky. I didn't know it is even possible. Thanks!

**Comment by develohpanda** [comment]
Yes! Work in progress, we'll have this fixed up as soon as we can though! :)

**Comment by maxxyme** [comment]
Note: same problem with importing a WSDL file (= for a SOAP webservice); your workaround explained above (choosing "current workspace") does the job.

**Comment by mrlinnth** [comment]
> The old UI flow still works though. Create a request collection, go to it, click it's name in the top bar, click "Import/Export" and import requests from there.

Thank you. This helped me.

**Comment by gh-andre** [comment]
This issue is closed, but all attempts to import, whether within a project or into a new collection, as described above in a work-around, yield the same effect - it lists all things that supposedly were imported and project or collection remain empty.

I'm running the latest Insomnia v2021.6.0. Anyone has any thoughts on what's going on?

**Comment by develohpanda** [comment]
Hi @gh-andre! This has been resolved and merged into the main branch however has not been released yet. We have a release planned in the next week or two and that will include a fix to this! Thank you for your patience and apologies for any inconvenience  🙌🏽

**Comment by blshkv** [comment]
@develohpanda I know it's open source, "dont use if you don't like it" and all that, but ...  "postman" mentioned 3 (!!!) times on the homepage, so people expect it to be a postman **reliable** alternative. Bugs like this should be your highest priority and should be fixed within days, not months.

**Comment by gh-andre** [comment]
@develohpanda Thanks for clarifying. I gathered after posting that this is the case. GitHub doesn't make it easier to track what's released and what's on its way to be released. Looking forward to this release - it makes it tricky to share test scripts when they can't be imported.

**Comment by develohpanda** [comment]
@blshkv Thanks for the feedback, I completely understand the frustration. To share some background, this case was an underlying bug impacting several import formats and not specifically for Postman, which made the fix for it a bit involved and extended the dev + review + QA process to ensure we have a stable fix. Once we have a stable fix though we should be able to release it faster. Although we are a small team, more frequent releases is high on our priority list, which will help in getting new features and fixed bugs resolved for end users as fast as possible once they merge. Keep an eye out for improvements here in 2022! 🙌🏽 

@gh-andre no worries! It really can be tricky. I've hit this issue more than once. We haven't got a practice of using milestones in GitHub which would help here, perhaps something we can look into!

**Comment by gh-andre** [comment]
@develohpanda Just an FYI, I just tried `2021.7.0-beta.0` and it still won't import previously exported Insomnia v4 YAML, even though it says that it imported everything that is in that file in the pop-up at the end of import. Same behavior for request collections and design documents.

**Comment by develohpanda** [comment]
Hi @gh-andre, thanks for checking on the beta build. Could you please share your exact reproduction steps?

**Comment by gh-andre** [comment]
I'm not doing anything special, really. Here's what I tried:

* Export a request collection as v4 YAML or JSON
* Create a new collection and try to import in various ways (Import from File button, Settings menu)
* Pop-up is presented that says _Import Succeeded_ and further _You imported 1 Workspace, 3 Environments, 1 Cookie Jar, 1 ApiSpec, 5 Folders, 21 requests_

I tried this in different combinations, from projects, default project, design docs and request collections and the outcome is the same.

One strange thing is that the exported collection doesn't have a design document, which is reported in the import counts. Based on this hunch I hacked the export removing bits and pieces one-by-one and finally found one change that makes import successful to some extent (I don't know how much is broken behind the scenes, though).

When I replace `parentId` values with `null` values, then it imports. That is, in the entire exported YAML, I replaced all parents, regardless of their type (i.e. `wrk`, `fld`, etc), so this:

    parentId: wrk_05a394de28cd45eea314d74397144b40

, becomes this:

    parentId: null

After this it got requests in, but, of course, folders weren't populated, given how I removed the folder parents. Armed with this knowledge, I replaced just `wrk` parents, which got me all folders as well, but environments weren't selected. 

It seems to me there's something wrong with the parent workspace. Maybe it still uses the old parent?

**EDIT**: I caution from using these tests as a workaround - Insomnia may confuse various IDs and may delete source workspaces because of this mix-up. I got one of mine emptied this way.

**Comment by gh-andre** [comment]
Also, unrelated, in design specs, those buttons at the top (Design, Debug, Test) got much, much smaller than they were before. Doesn't seem this is intentional, so just another FYI.

**Comment by gh-andre** [comment]
@develohpanda Sorry, forgot to mention in the above. 

I think I can reproduce this and it's a pretty bad bug. I lost some data and I think others may have lost data too without realizing it.

I reverted to Insomnia 2021.6.0 for these tests.

* Create a test request collection and name it `ABC`. Don't use any with good requests.
* Add a couple of requests.
* Export `ABC` as v4 YAML.
* Rename `ABC` to `XYZ` in collection settings and add something to collection description.
* Create an empty collection `EMPTY`
* Within `EMPTY`, click `Import from File` and select `ABC` exported YAML.
* The collection `EMPTY` remains empty, as if the import fails.
* Switch to the dashboard. `XYZ` no longer exists and was reverted to `ABC` and the new description is gone.

The original collection is replaced with the contents of the exported YAML, including any requests that may have been modified.

Seems that Insomnia is confusing workspaces and silently overwrites the original collection, so it seems like the import failed, but it actually trashes the original collection.

**Comment by develohpanda** [comment]
@gh-andre thanks for the steps there. The import works with ids, so in your example the workspace id already existed (although renamed) and it was updated to match the contents of the export. I tried this myself and was able to see the behavior you described.

I can see how this can cause issues though; the example you had was changing only the workspace name and description, but the same could happen with requests. It won't delete anything new that you've created (environments, requests, etc), but it could overwrite any edits you've made to existing ones, where the _id can be found in the export file.

I think what you're after is potentially something that imports into the active workspace explicitly. Ie. from your example, `Empty` should contain the things being imported, and `XYZ` remains untouched. Your exact reproduction steps are useful; could you please create a new issue using that? It doesn't relate directly to this issue (which is to do with importing from outside Insomnia - curl, postman, wsdl, etc), which has been resolved.

**Comment by gh-andre** [comment]
@develohpanda Hmm... It sounds like you are saying that this might be by design. This is surprising. If I click _Import from File_ in a new collection, I expect this collection to get the imported data, not the original collection modified silently in background and without any warning, I might add.

What you are describing is a backup feature - one can backup their collections and restore. It should warn that some data may be lost if the user proceeds with restoring data. Some of the edits may be quite extensive, as I have learned after losing them.

It also means that I cannot import a request collection into a design document. Say, I have a collection with dozens upon dozens of requests and I decided to start a new project and organize all around a design document. It turns out I cannot because import only works as a backup and one cannot *import* anything, only *restore* original collections.

I guess I need to figure out how I can move data between collections, aside from using HAR, which loses all metadata. Didn't expect this, to be honest.

**Comment by develohpanda** [comment]
Ah, I agree that the behavior you have hit is not desirable, and I agree that if Insomnia detects there is some existing data that may be overwritten, it should prompt and ask what to do (for example). I've raised this concern internally with the team already.

I'm sorry that as a result of this you've ended up losing your edits, I understand how frustrating that can be and we as a team want to avoid situations like that as much as possible. Understanding these workflows and handling each workflow is something we continuously work on.

The last note about moving data between collections and documents is key as well. Because something like that isn't built-in to the app, workarounds (such as export/import) need to be used, which landed you in this state, and any time a workaround is being used, we should revisit that flow.

If you could please raise a new bug report describing your reproduction steps we would really appreciate that. Then, I'll drive some discussions internally and we can figure out how to improve this workflow to be much, much more defensive. As we work through that and a PR gets created, you'll see it be linked to the new issue.

**Comment by gh-andre** [comment]
@develohpanda Will do. Thanks for your thoughts.

**Comment by Manikese** [comment]
Hello all.  I'm reaching out here as my last attempt before uninstalling.  The past few months I have tried and was unsuccessful in importing my old collections.  I've been using postman since 2017.  My collections disappeared with an auto update Postman did.  I've tried importing, creating a request collection then importing, and each time it says that it is successful.  But nothing I do gets any of my collections containing my api requests to show in the application.  Any help would be very much appreciated.  This is my version info:

Postman for Windows
Version 9.13.2
UI Version 9.13.2-ui-220214-1351
Desktop Platform Version 9.13.0
Architecture x64
OS Platform win32 10.0.18363

**Comment by msdme** [comment]
Hi, maybe this clip can help someone to display a collection that you have imported but is not showing up. Simply drag on the edge points like the following clip.

![insomnia-import-no-collection](https://github.com/user-attachments/assets/6aef16c9-f390-4048-a794-8829409e93be)
