### ISSUE TITLE
2022.7.0 Render failure

### ISSUE THREAD

**Issue by slaphead** [getinsomnia/insomnia#5553]
### Expected Behavior

Send HTTP requests using the dialog box in the center view.

### Actual Behavior

I am unable to see the send request dialog box on any of my requests.

On the graphql calls the entire section where the queries are set does not load.
On standard HTTP calls, the section does not load either.

<img width="1573" alt="Screenshot 2022-12-19 at 11 52 48 AM" src="https://user-images.githubusercontent.com/10655963/208478210-0bda95f3-b959-4033-aa99-14bb0cef9b61.png">

### Reproduction Steps

1. Open insomnia
2. Go to any request and I cannot see the option to send an HTTP call.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

I tried reloading insomnia and cannot get this view to show. I have not had time to try and deeply troubleshoot this, but will try and see if I can find a workaround.

### Insomnia Version

2022.7.0

### What operating system are you using?

macOS

### Operating System Version

Ventura 13.1

### Installation method

Downloaded from insomnia.rest

**Comment by slaphead** [comment]
Ugh it seems I was too quick to log this. After a third reload it seems fine now. Not sure how to explain what went wrong. Will close this for now

**Comment by slaphead** [comment]
Looks like this is still happening. After opening the app and using it for a few minutes, I get the error again. Here is a stack trace:
```
Error: Input Object type DataPackageMetaInputCreate must define one or more fields.
    at nR (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:504:12630)
    at y_ (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:506:43944)
    at AK (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:635:356)
    at FK (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:641:211)
    at Object.DTe (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:641:147)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:646:2557
    at x (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:431:14293)
    at ii.<anonymous> (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:431:16262)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:407:10355
    at ii.setOption (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:412:1978)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:671:5056
    at mE (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:67:24458)
    at nh (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:67:42799)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:67:41058
    at A (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:52:1648)
    at Immediate.ce [as _onImmediate] (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:52:2022)
    at process.processImmediate (node:internal/timers:466:21)
```

**Comment by PrinceGvidon** [comment]
I got same problem after update Insomnia to 2022.7.0 on my macOS Monterey 12.3.1.


**The application is displayed like this:**
<img width="1081" alt="Снимок экрана 2022-12-20 в 13 06 38" src="https://user-images.githubusercontent.com/90255562/208640817-805ab933-396b-402f-95c9-d1d7e21b7173.png">

**Stack trace:**
`GraphQLError: Value "2b4e4216-1ecc-4252-9374-4668f444a88f" does not exist in "ProductName" enum.
    at Yl.parseValue (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:502:10797)
    at Vm (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:646:20522)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:646:19879
    at Array.map (<anonymous>)
    at H5 (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:646:20809)
    at Vm (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:646:19659)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:646:19879
    at Array.map (<anonymous>)
    at H5 (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:646:20809)
    at Vm (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:646:19659)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:646:19879
    at Array.map (<anonymous>)
    at H5 (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:646:20809)
    at Vm (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:646:19659)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:646:19019
    at Array.forEach (<anonymous>)
    at UCe (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:646:18928)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:646:18866
    at x (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:431:14293)
    at ii.<anonymous> (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:431:16262)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:407:10355
    at ii.setOption (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:412:1978)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:671:5056
    at mE (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:67:24458)
    at nh (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:67:42799)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:67:41058
    at A (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:52:1648)
    at Immediate.ce [as _onImmediate] (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:52:2022)
    at process.processImmediate (node:internal/timers:466:21)
`

**Comment by ngAlpine** [comment]
Also getting this on Windows 11 Pro. Can post stack trace on request, but it is nearly identical to what slaphead posted.

**Comment by nik-lampe** [comment]
Same Issue, 2022.7.0.
MacOS 13.0.1, but I think that's not relevant.

In my case the data entered in the variables do not conform the required input types of my GQL Query. But because of the render Error I can't change it anymore :D 

```
GraphQLError: Value "null" does not exist in "DLLCreditGroup" enum.
    at Yl.parseValue (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:502:10797)
    at Vm (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:646:20522)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:646:19879
    at Array.map (<anonymous>)
    at H5 (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:646:20809)
    at Vm (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:646:19659)
    at Vm (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:646:19335)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:646:19879
    at Array.map (<anonymous>)
    at H5 (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:646:20809)
    at Vm (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:646:19659)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:646:19879
    at Array.map (<anonymous>)
    at H5 (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:646:20809)
    at Vm (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:646:19659)
    at Vm (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:646:19335)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:646:19019
    at Array.forEach (<anonymous>)
    at UCe (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:646:18928)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:646:18866
    at x (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:431:14293)
    at ii.<anonymous> (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:431:16262)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:407:10355
    at ii.setOption (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:412:1978)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:671:5056
    at mE (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:67:24458)
    at nh (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:67:42799)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:67:41058
    at A (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:52:1648)
    at Immediate.ce [as _onImmediate] (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.7cb7367d.js:52:2022)
    at process.processImmediate (node:internal/timers:466:21)
```

**Comment by bhurlow** [comment]
Getting the same issue too. It unfortunately a show stopper because I can't edit the query variables to rectify

**Comment by visoft** [comment]
Mine is crashing the 2022.7.0 app when it auto-pulls the schema. I reverted to 2022.6.0, and everything works as expected.

**Comment by bhurlow** [comment]
I also reverted back to `2022.6.0`

**Comment by thornomad** [comment]
I had same problem and had to revert to `2022.6.0` in order to be unblocked.

**Comment by tikhepooja11** [comment]
pls let me know the solution getting render failure issue

**Comment by filfreire** [comment]
Hi folks, are you still able to reproduce this in version `2022.7.1`? Some of the cases for this render failure should be working now.

**Comment by filfreire** [comment]
Might be fixed in https://github.com/Kong/insomnia/pull/5650

**Comment by slaphead** [comment]
Thanks for getting a fix out! I will test asap!

**Comment by slaphead** [comment]
It's still happening :(
<img width="766" alt="Screenshot 2023-01-11 at 1 08 12 PM" src="https://user-images.githubusercontent.com/10655963/211884425-4c36fea1-fc4a-484c-8404-2b1856d7cf36.png">
 Here is the stack trace in text:
 ```
 Error: Input Object type DataPackageMetaInputCreate must define one or more fields.
    at PO (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.45c40456.js:524:12630)
    at t_ (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.45c40456.js:526:43944)
    at YV (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.45c40456.js:655:356)
    at rK (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.45c40456.js:661:211)
    at Object.Lke (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.45c40456.js:661:147)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.45c40456.js:666:2557
    at x (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.45c40456.js:451:14293)
    at Zr.<anonymous> (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.45c40456.js:451:16262)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.45c40456.js:427:10355
    at Zr.setOption (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.45c40456.js:432:1978)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.45c40456.js:691:5056
    at eE (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.45c40456.js:67:24458)
    at Yp (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.45c40456.js:67:42799)
    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.45c40456.js:67:41058
    at I (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.45c40456.js:52:1648)
    at Immediate.ue [as _onImmediate] (file:///Applications/Insomnia.app/Contents/Resources/app.asar/index.45c40456.js:52:2022)
    at process.processImmediate (node:internal/timers:466:21)
 ```

I double checked it is on `2022.7.1`

**Comment by klaucode** [comment]
I have the same problem :-(

**Comment by andrewsmd8** [comment]
@klaucode we've worked around this in the short term by using the beta version of the application. Just go to application -> preferences and change this
![image](https://user-images.githubusercontent.com/8485461/213724478-3526d66b-bebe-49cf-a579-c6003ca52c5c.png)

**Comment by filfreire** [comment]
Hi folks, this particular render failure issue on GraphQL requests should not be happening in [latest 2022.7.5 release](https://github.com/Kong/insomnia/releases/tag/core%402022.7.5)

**Comment by klaucode** [comment]
> Hi folks, this particular render failure issue on GraphQL requests should not be happening in [latest 2022.7.5 release](https://github.com/Kong/insomnia/releases/tag/core%402022.7.5)

Thanks a lot for your reply, update helped :-)
