### ISSUE TITLE
Filter no longer working in 2023.5.2

### ISSUE THREAD

**Issue by brianGit78** [getinsomnia/insomnia#6291]
### Expected Behavior

When inputting a text string in the filter to search through my list of 5000 calls, I should see only the calls that the filter applies to

### Actual Behavior

I see all of my calls, they are not filtered out as expected. I do see the text bolded and underlined in the call list. This new behavior does not work for a large list of calls. This only started happening on the release I updated this morning. 

### Reproduction Steps

1. Go to my collection
2. input text in the filter text input box
3. list no longer filters

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.5.2

### What operating system are you using?

Windows

### Operating System Version

Windows 11 latest patches

### Installation method

download and install

**Comment by jamietwells** [comment]
Yes, feels like the same as 

https://github.com/Kong/insomnia/issues/5851

filtering removed for no reason. This software is becoming unusable with a large collection.

**Comment by izaacsilva** [comment]
You should remove the 2023.5.2 release until solve this problem.

**Comment by tsptylertech** [comment]
This is happening for me too...

**Comment by hippasus** [comment]
same here... Mac OS with Insominia 2023.5.2

**Comment by pavelToman** [comment]
same problem on Ubuntu 22.04.3 LTS - even can not manually change the position of requests

**Comment by CaiqueCastro07** [comment]
Same here, mac os mojave in these last days updates...

**Comment by srinu-ac50765** [comment]
Same problem. Windows with latest update.

Version: Insomnia 2023.5.3
Build date: 8/16/2023
OS: Windows_NT x64 10.0.19045
Electron: 25.2.0
Node: 18.15.0
Node ABI: 116
V8: 11.4.183.23-electron.0
Architecture: x64

**Comment by gogvale** [comment]
Same here:
---
Version: Insomnia 2023.5.3
Build date: 8/16/2023
OS: Darwin x64 22.4.0
Electron: 25.2.0
Node: 18.15.0
Node ABI: 116
V8: 11.4.183.23-electron.0
Architecture: x64

Edit: This version works for me: https://github.com/Kong/insomnia/releases/tag/core%402023.4.0

**Comment by PokimonZerg** [comment]
# Same here

Version: Insomnia 2023.5.3
Build date: 16.08.2023
OS: Windows_NT x64 10.0.22621
Electron: 25.2.0
Node: 18.15.0
Node ABI: 116
V8: 11.4.183.23-electron.0
Architecture: x64

This is big regression problem. Please, take attention to it.

**Comment by johnnovak** [comment]
+1 this should be fixed urgently, please.

This makes Insomnia virtually unusable. The query switching popup menu thing doesn't work either...

**Comment by ppakorn** [comment]
This makes the app unusable because I have hundreds of requests

Version: Insomnia 2023.5.3
Build date: 8/16/2023
OS: Darwin x64 22.4.0
Electron: 25.2.0
Node: 18.15.0
Node ABI: 116
V8: 11.4.183.23-electron.0
Architecture: x64

**Comment by johnnovak** [comment]
> This makes the app unusable because I have hundreds of requests

Yeah I literally have hundreds of requests organised into folders, and I rely on the search 99% of the time. That plus Ctrl+Tabbing between the requests... Both are now non-functional.

Also, please fix the searching between the environments in the envs dropdown. I also have 50+ environments and the environment search has been broken for a while now. Also, at least show the list sorted, or fix the drag'n'drop reordering of environments as it's _massively_ buggy.

This was all working 100% fine like a year ago, so this is not really progress...

**Comment by xinsight** [comment]
Still broken in 2023.5.3

Version: Insomnia 2023.5.3
Build date: 8/16/2023
OS: Darwin arm64 22.5.0
Electron: 25.2.0
Node: 18.15.0
Node ABI: 116
V8: 11.4.183.23-electron.0
Architecture: arm64

**Comment by fernandosmace** [comment]
I just heard about this bug today.

I'm working on a fix for this and soon will send the PR.

**Comment by dannygpm** [comment]
Facing the same issue.

**Comment by filfreire** [comment]
duplicate of #6288

**Comment by JuMp3** [comment]
Hi, 
i just updated insomnia to the latest version (2023.5.4), yet i keep having the same problem; you too?

![image](https://github.com/Kong/insomnia/assets/13451331/490a17c3-9f47-483c-89b0-98d2b84310ec)

Also I noticed that now I can't move both folders and requests to positions I want.

**Comment by tsptylertech** [comment]
This is still not working for me either...

**Comment by ppamorim** [comment]
It's broken for me. Please fix.
