### ISSUE TITLE
[Bug] GET requests hanging with no reason

### ISSUE THREAD

**Issue by rafaelrenanpacheco** [getinsomnia/insomnia#633]
- Insomnia Version: v5.12.0
- Operating System: Ubuntu 17.04

## Details

After updating to v5.12.0, the GET requests are hanging with no reason, and at random. If I shut down my server, the GET request doesn't even returns a 404, it just keeps loading and loading forever. If I close and reopen Insomnia, and press "Send" to the first GET request I have, it stays forever loading as well.

To "unlock" the GET requests, I have to send a POST request to some other API. Then the GET requests start to work again, for a little time, until they start to hang again.

Is there any log I can check to see the reason for this issue? The "DevTools" doesn't show anything about this weird issue.

Best regards,
Rafael Pacheco.

**Comment by gschier** [comment]
Hmm, I think I've seen something like this before in the past. Can you post the log from the Timeline view (hiding any sensitive information)?

Also, for now you can download a previous version from https://github.com/getinsomnia/insomnia/releases/tag/v5.11.7

**Comment by rafaelrenanpacheco** [comment]
I waited for 200 seconds, but it doesn't seem it would end.

So I pressed the cancel button to get the Timeline log, but since I the connection was canceled, it doesn't show anything good:

```
* Preparing request to http://localhost:8000/user
* Using libcurl/7.52.1 OpenSSL/1.0.2g zlib/1.2.11 libidn2/0.16 libpsl/0.17.0 (+libidn2/0.16) librtmp/2.3
* Enable automatic URL encoding
* Enable SSL validation
* Enable cookie sending with jar of 0 cookies
* Curl_http_done: called premature == 1
* Closing connection 10
```

As you suggested, I'll rollback to 5.11.7 :+1:

**Comment by gschier** [comment]
Thanks. Was mostly interesting in the curl version etc. Looks like there was a problem with the build on Windows not linking the correct version.

**Comment by gschier** [comment]
Hey @rafaelrenanpacheco. I just pushed a build that I hope fixes the problem (I can't reproduce it). Can you give it a try and let me know if it works? https://github.com/getinsomnia/insomnia/releases/tag/v5.12.1

**Comment by gschier** [comment]
Sorry, disregard that. For some reason I thought you were on Windows. I'll keep digging.

**Comment by rafaelrenanpacheco** [comment]
Hi @gschier!

I'll try the v5.12.1 later today.

Thanks!

**Comment by rafaelrenanpacheco** [comment]
Updated to v5.12.3, and the problem is still there.

Here is the timeline output:

```
* Preparing request to http://localhost:8000/logout
* Using libcurl/7.52.1 OpenSSL/1.0.2g zlib/1.2.11 libidn2/0.16 libpsl/0.17.0 (+libidn2/0.16) librtmp/2.3
* Enable automatic URL encoding
* Enable SSL validation
* Enable cookie sending with jar of 0 cookies
* Hostname in DNS cache was stale, zapped
* Curl_http_done: called premature == 1
* Closing connection 25
```

v5.11.7 doesn't have this issue.

Best regards,
Rafael Pacheco.

**Comment by gschier** [comment]
Wow that's so strange. I can't think of anything else off the top of my head that would affect that.

Can you let me know if either of these work when you get a chance?

https://insomnia.rest/changelog/5.12.0-beta.2/
https://insomnia.rest/changelog/5.12.0-beta.3/

I'll keep thinking about this in the meantime.

**Comment by gschier** [comment]
Just a few more questions so I can try to reproduce on my end.

- Does this happen on every URL you contact?
- If only on localhost, what type of server are you running?
- Can you post the first few lines of logs from a successful request as well?

**Comment by rafaelrenanpacheco** [comment]
Hi @gschier!

> Does this happen on every URL you contact?

It happens for all URLs which uses OAuth2 with Resource Owner Password Credentials. I only have one route which doesn't use OAuth2, the `/login` route. For the login route I never saw it hanging.

> If only on localhost, what type of server are you running?

I'm serving directly from PHP, using Laravel's `php artisan serve` on localhost. But as I said before, if I turn off the server, the request still hanging and doesn't return a 404.

> Can you post the first few lines of logs from a successful request as well?

```
* Preparing request to http://localhost:8000/tags
* Using libcurl/7.52.1 OpenSSL/1.0.2g zlib/1.2.11 libidn2/0.16 libpsl/0.17.0 (+libidn2/0.16) librtmp/2.3
* Enable automatic URL encoding
* Enable SSL validation
* Enable cookie sending with jar of 0 cookies
* Hostname localhost was found in DNS cache
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8000 (#135)
> POST /tags HTTP/1.1
> Host: localhost:8000
> User-Agent: insomnia/5.12.3
> Accept: application/json
> Content-Type: application/json
> Authorization: Bearer <hided>
> Content-Length: 18
| {
| 	"name": "tag"
| }
* upload completely sent off: 18 out of 18 bytes
< HTTP/1.1 201 Created
< Host: localhost:8000
< Connection: close
< X-Powered-By: PHP/7.0.22-0ubuntu0.17.04.1
< Cache-Control: no-cache, private
< Date: Tue, 28 Nov 2017 22:39:44 GMT
< Location: http://localhost:8000/tags/20
< Content-Type: text/html; charset=UTF-8
< X-RateLimit-Limit: 60
< X-RateLimit-Remaining: 58

* Received 0 B chunk
* Curl_http_done: called premature == 0
* Closing connection 135
```

**Comment by gschier** [comment]
@rafaelrenanpacheco do you see any errors in the app in the new version? You can check via View > Toggle DevTools > Console.

**Comment by gschier** [comment]
Dang. Yep, I see the problem. If you're curious, the issue is from the GraphQL library doing an `if (something instanceof GraphQLSchema) {...}` but it fails because there are two libraries that define `GraphQLSchema`. I fixed this last time by doing an `npm dedup` before the build but that's proving to be a very brittle solution. going to need to find a more stable fix.

<img width="517" alt="image" src="https://user-images.githubusercontent.com/587576/33352307-23a35fd0-d4a0-11e7-8e84-7d67cc2aec56.png">

**Comment by janpieterz** [comment]
I'm seeing this as well, on Windows.
Switching to other request or, funny enough, cancelling seems to 'break it free'.
Using version 5.12.3, but also on previous version and manually tested the one mentioned here https://github.com/getinsomnia/insomnia/issues/633#issuecomment-347388809

Using OAuth Client Credential flow, but not been able to reliably reproduce so far. Happens on all kind of urls (no non-oauth one on this). Running ASP.NET core 2.x.

**Comment by gschier** [comment]
> Edit: While the request is hanging, if I change to another request the locked request unlocks. So, just switching to another tab solves the problem. The console doesn't show any output while it is loading, and no error output after the unlock technique.

@rafaelrenanpacheco Can you clarify what you mean by this? Are you saying that the request finishes immediately (and successfully) if you switch to another request and back? Do you have to send the other request or does the simple act of switching to one in the sidebar work?

> Using version 5.12.3, but also on previous version and manually tested the one mentioned here

@janpieterz are you saying that this was happening to you before v5.7.11?

**And one last clarification question:** Have either of you seen this happen on a non-oauth request?

**Comment by rafaelrenanpacheco** [comment]
> Are you saying that the request finishes immediately (and successfully) if you switch to another request and back?

Exactly. I don't even need to press send to unlock the bugged request. Just switching to another request and back solves the issue.

> Have either of you seen this happen on a non-oauth request
I only have one non-oauth route (/login), and on that route I never saw this issue. I only saw this issue on oauth2 routes.

**Comment by gschier** [comment]
Today I set up PHP/laravel on my Mac, served with artisan, mocked up a fake OAuth endpoint, and was able to reproduce the described problem! My first thought is that it has to do with opening more than one connection to a webserver than is single-threaded (causing deadlock). Going to debug and will report back what I find.

**Comment by starJammer** [comment]
I was going to chime in and say I'm seeing the same issue occur on Mac OS 10.10.5 with v5.12.3 of Insomnia.

As @rafaelrenanpacheco said, switching the selected request in the sidebar causes the hung request to actually run.

**Comment by gschier** [comment]
Can one of you verify whether or not the request is making it to your server before switching to another request?

**Comment by gschier** [comment]
I was able to reproduce it a few times but now it seems to be working as expected again :(

**Comment by rafaelrenanpacheco** [comment]
In my test it didn't reach the server, because the server didn't logged anything. The best way to ensure this is just to shutdown the server and send a request. Insomnia will still hang trying to connect to the shutdown server.

**Comment by rafaelrenanpacheco** [comment]
I found a way to always simulate this problem. Start up your server and send a request. After that, close the Insomnia instance and open it again, pressing Send to the previously selected request. I did this 5 times and it hung in all 5 times.

Also I found another way to unlock the request. Just collapse and expand some request folder, and the locked request goes free.

**Comment by gschier** [comment]
Thanks for the reply. It confirmed my suspicion. I'm pretty sure the problem is at the DNS level. I configured libcurl to disable the DNS cache `CURLOPT_DNS_CACHE_TIMEOUT = 0` and I can now get the request to hang every time. 

It seems that there is something wrong with an internal part that I don't understand. When it's hanging, basically anything that triggers the NodeJS event loop "fixes" it. Even something as simple as `process.nextTick(() => {})`. Currently digging in further to narrow down the cause.

**Comment by gschier** [comment]
Pushing a beta build for this now

**Comment by gschier** [comment]
Can one of you try this and let me know if it fixes the issue? https://github.com/getinsomnia/insomnia/releases/tag/v5.12.4-beta.1

**Comment by rafaelrenanpacheco** [comment]
Looks like it is working fine now! :smiley: 

Restarted Insomnia a few times, and the send request didn't hang.

**Comment by gschier** [comment]
Wicked! That's a huge relief. I'll push an official release tomorrow 😁

Thanks for testing that out

**Comment by janpieterz** [comment]
Apologies for the late response, confirmed here too with above beta.
