### ISSUE TITLE
Error syncing with Insomnia Cloud

### ISSUE THREAD

**Issue by mrjimhubbard** [getinsomnia/insomnia#6955]
### Expected Behavior

Project should sync with Insomnia cloud when Secure Cloud is selected for the project.

### Actual Behavior

I am getting an error in bottom left corner saying "Error syncing with Insomnia Cloud"
![i7 SNAG- 12-30-2023 10 34 42 PM](https://github.com/Kong/insomnia/assets/90149731/c6ab54db-343d-447b-bf13-4a7a8d535856)

Even though the project was created to sync with the cloud.... 
![i7 SNAG- 12-30-2023 10 33 13 PM](https://github.com/Kong/insomnia/assets/90149731/71f34331-a094-4232-9eb8-6fb29b7570a3)

### Reproduction Steps

I just opened Insomnia - after it made me use secure login again. I guess I need to record my entire coding sessions now if I use Insomnia...

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

There is a similar issue at https://github.com/Kong/insomnia/issues/6842 - but no mention of the error message.

It would be really nice if we could do these reports from inside Insomnia - maybe with screenshots and let it upload all the info you need....

### Insomnia Version

8.5.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 22H2

### Installation method

download from the website

### Last Known Working Insomnia version

unknown

**Comment by yonatanaduk** [comment]
Hi, i have this problem also.

**Comment by subnetmarco** [comment]
This shouldn't happen - does this happen if you create a new collection? It seems that you ended up in an inconsistent state due to mishandling on an error state from our part.

**Comment by ryuuusagi** [comment]
I'm experiencing the exact same issue in Windows 10 build 10240. Insomnia version 8.5.1, like OP. Additionally, when trying to create a new collection, I get this error message:

> Error: Failed to deserialize key=/projects/prj_96be9d7f1afe4b54b203e591b0602384/meta.json err=SyntaxError: Unexpected token '', ""... is not valid JSON at H$e.getItem (file:///C:/Users/IABE/AppData/Local/insomnia/app-8.5.1/resources/app.asar/index-f6dc2321.js:509:23710) at async j5._allBackendProjects (file:///C:/Users/IABE/AppData/Local/insomnia/app-8.5.1/resources/app.asar/index-f6dc2321.js:666:3015) at async j5._getBackendProjectByRootDocument (file:///C:/Users/IABE/AppData/Local/insomnia/app-8.5.1/resources/app.asar/index-f6dc2321.js:666:2135) at async j5._getOrCreateBackendProjectByRootDocument (file:///C:/Users/IABE/AppData/Local/insomnia/app-8.5.1/resources/app.asar/index-f6dc2321.js:666:2704) at async j5.switchAndCreateBackendProjectIfNotExist (file:///C:/Users/IABE/AppData/Local/insomnia/app-8.5.1/resources/app.asar/index-f6dc2321.js:509:30515) at async D$e (file:///C:/Users/IABE/AppData/Local/insomnia/app-8.5.1/resources/app.asar/index-f6dc2321.js:509:20176) at async Module.Ze (file:///C:/Users/IABE/AppData/Local/insomnia/app-8.5.1/resources/app.asar/actions-75c6cc4c.js:4:8445) at async H8 (file:///C:/Users/IABE/AppData/Local/insomnia/app-8.5.1/resources/app.asar/index-f6dc2321.js:55:3729) at async q (file:///C:/Users/IABE/AppData/Local/insomnia/app-8.5.1/resources/app.asar/index-f6dc2321.js:54:20308)

![image](https://github.com/Kong/insomnia/assets/130121055/82d23464-af50-44de-a254-a54c74214001)

**Comment by notjaywu** [comment]
@mrjimhubbard Is `Streamline` an existing collection or a newly created one?

**Comment by notjaywu** [comment]
> Hi, i have this problem also.

@yonatanaduk could you provide more details:
1. What is your account email address?
2. Which project can't sync with Insomnia Cloud?

Can `Duplicate` solve this issue?
<img width="244" alt="image" src="https://github.com/Kong/insomnia/assets/130019718/80d07b59-7ca0-4c83-a40c-43964d51a36f">

**Comment by yonatanaduk** [comment]
hi @notjaywu

It's happened to me on the account of my team,  we have a few collections, and all of them with the same error
I tried to duplicate it but still have the same error

![image](https://github.com/Kong/insomnia/assets/84029275/ef5d504a-2438-4b30-b3b7-96aac50c5e93)

**Comment by gabdanReply** [comment]
I have the same Issue

**Comment by notjaywu** [comment]
@yonatanaduk @gabdanReply Could you share what you did before this issue happened?

**Comment by gabdanReply** [comment]
> @yonatanaduk @gabdanReply Could you share what you did before this issue happened?

nothing, we used the application normally

**Comment by gatzjames** [comment]
@gabdanReply if you open the menu it should display a more verbose error.
Can you share the error it will help us debug the reason this issue is happening.

**Comment by bangprovn** [comment]
My project is having the same issue, the only thing I did is switching from syncing between macOS and Windows. Now all of my project can't sync

**Comment by yonatanaduk** [comment]
@gatzjames 
I opened the devs tool and this is what i see : 

![image](https://github.com/Kong/insomnia/assets/84029275/0d99899d-9ca7-4240-81bc-fbd730dc4c1e)

**Comment by yonatanaduk** [comment]
@gatzjames i deleted all the files from my PC, Download Insomnia again and the problem solved

![image](https://github.com/Kong/insomnia/assets/84029275/146be8ee-b029-4f67-af56-580cbc8760d5)

**Comment by stuart201** [comment]
I have this same issue

**Comment by abdullahmvn** [comment]
These steps solved my problem

1. Insomnia Menu -> Help -> Show App data folder = delete the selected folder
3. Insomnia Menu -> Help -> Show App logs folder = delete the logs folder

**Comment by arif-mvn** [comment]
> These steps solved my problem
> 
> 1. Insomnia Menu -> Help -> Show App data folder = delete the selected folder
> 2. Insomnia Menu -> Help -> Show App logs folder = delete the logs folder

@abdullahmvn  Thanks bro..........Saved my time and energy.

**Comment by m0hammed-ragab** [comment]
> These steps solved my problem
> 
> 1. Insomnia Menu -> Help -> Show App data folder = delete the selected folder
> 2. Insomnia Menu -> Help -> Show App logs folder = delete the logs folder

work fine thanks @abdullahmvn

**Comment by notjaywu** [comment]
It should have been fixed in v9.0. Close this issue.

**Comment by scottie** [comment]
Still the same results in 9.1.0 @notjaywu

**Comment by notjaywu** [comment]
hi @scottie, could you share the screenshot of the console errors here? If it happened before upgrading to 9.1.0, you have to follow @abdullahmvn 's steps above to repair this issue.

<img width="1728" alt="Screenshot 2024-05-13 at 09 31 25" src="https://github.com/Kong/insomnia/assets/130019718/c8ba8297-a60a-46ca-b25e-d5599284d75c">

**Comment by skiat** [comment]
Hello there,
it happened to me (v9.2.0) and was able to fix coping the meta.json data from the latest meta.json.XXXXXXXXX.tmp

so that I avoided to reinstall and setup everything ;)

**Comment by subnetmarco** [comment]
@notjaywu @gatzjames this issue still persists, re-opening the ticket.

**Comment by rich-grundy-paytently** [comment]
I'm seeing a similar issue today when trying to migrate our team over to Insomnia from Postman, seeing the following sync error and these in the console:

![image](https://github.com/Kong/insomnia/assets/168630986/e9d2b732-080b-40d2-a578-a730c0a30986)
![image](https://github.com/Kong/insomnia/assets/168630986/284427bb-3680-423a-b637-6488e5e1fcfe)
![image](https://github.com/Kong/insomnia/assets/168630986/da9b7758-b1ca-4e64-84b2-1b17361370c7)

Version: Insomnia 9.2.0 on iOS

Any help would be appreciated.

**Comment by notjaywu** [comment]
@rich-grundy-paytently The error shows that you don't have access to this collection.

**Comment by mrjimhubbard** [comment]
Me too - I don't guess it'll ever get fixed.

![i7 SNAG- 6-11-2024 7 45 19 AM](https://github.com/Kong/insomnia/assets/90149731/b9f7816a-ad5c-4aa9-bcf9-79664c2b52b3)

**Comment by rich-grundy-paytently** [comment]
> @rich-grundy-paytently The error shows that you don't have access to this collection.

It's my collection though

**Comment by subnetmarco** [comment]
@rich-grundy-paytently to add more information:

- Is this a collection in your personal workspace, an organization you created, or an organization you have been invited to (you are either an admin or a collaborator)?
- Was this collection working before, and it stopped working after a product update?

**Comment by rich-grundy-paytently** [comment]
@subnetmarco - 

Collection in my personal workspace. The plan is to invite my team as collaborators.

The collection worked fine and then when I came back to it later in the day I saw the above sync error message.
Finding this Github issue I followed the above suggestion of deleting the App data folder and Logs and restarted the application. However when I logged back into my account while the Workspace existed there were no collections...

At this point I reimported the collection and continued, after pushing multiple commits successfully and using the application I then get this error again and I'm back to square one

Please let me know if you need any other details, thanks!

**Comment by notjaywu** [comment]
@rich-grundy-paytently Could you join our community Slack channel via https://chat.insomnia.rest, I can DM you for more details, thanks.

**Comment by rich-grundy-paytently** [comment]
@notjaywu - Done, feel free to message me

**Comment by notjaywu** [comment]
This issue has been fixed. If you encounter this issue, please duplicate the affected collections or documents, thank you!
![image](https://github.com/Kong/insomnia/assets/130019718/a2ecac23-1443-41a1-a851-bf9147c1e1e7)

**Comment by notjaywu** [comment]
@mrjimhubbard Can you try to duplicate the collection? If it isn't fixed, please also try the method provided by @abdullahmvn above.

**Comment by subnetmarco** [comment]
@rich-grundy-paytently are you running Insomnia on Windows?

**Comment by rich-grundy-paytently** [comment]
@subnetmarco - No, Mac iOS 13.5
This issue has now been resolved for me following some work by @notjaywu

**Comment by isadfrn** [comment]
> > These steps solved my problem
> > 
> > 1. Insomnia Menu -> Help -> Show App data folder = delete the selected folder
> > 2. Insomnia Menu -> Help -> Show App logs folder = delete the logs folder
> 
> work fine thanks @abdullahmvn

After trying this fix, I lost my collection, luckily my team colleagues had an copy and I was able to import the missing data. Seams that this is still happening on 9.2.0.

<img width="251" alt="Screenshot 2024-06-25 at 14 13 58" src="https://github.com/Kong/insomnia/assets/62663728/99040948-20c3-446c-bc8c-94d98273199a">

**Comment by notjaywu** [comment]
@isadfrn have you just upgraded from v8.3? or you have upgraded to v9.2 for a long time and this issue happened suddenly.

**Comment by isadfrn** [comment]
I've upgraded to v9.2 for a long time and this issue happened suddenly.

**Comment by marckong** [comment]
@isadfrn please DM us with your account email addresses. https://getinsomnia.slack.com

**Comment by bneumann** [comment]
Hey guys, I had the same problem and I solved it by removing the folder under %APPDATA%/Roaming/Insomnia. I exported all my collections first (just to be sure) and renamed that folder. So Insomnia came up clean again.
After that I connected to my account, downloaded the collections and used the import feature to apply my local changes. It doesn't complain anymore about not being connected now. Hopefully it stays that way

EDIT:
After 4 weeks I have the same error

**Comment by sohams98** [comment]
@notjaywu , that is not an acceptable solution. I should not have to duplicate collections or delete data as SOP. 

The issue still persists and I am currently facing it in Insomnia V10.0.0
![image](https://github.com/user-attachments/assets/24aef62a-5bed-4075-b5ea-8f3a8aaca8be)

Is there any timeline on when an actual fix will be implemented for this?

**Comment by notjaywu** [comment]
> @gatzjames I opened the devs tool and this is what i see :
> 
> ![image](https://private-user-images.githubusercontent.com/84029275/302553042-0d99899d-9ca7-4240-81bc-fbd730dc4c1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MDcyNzQsIm5iZiI6MTcyODcwNjk3NCwicGF0aCI6Ii84NDAyOTI3NS8zMDI1NTMwNDItMGQ5OTg5OWQtOWNhNy00MjQwLTgxYmMtZmJkNzMwZGM0YzFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA0MjI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5MjhmOWZhZTRjZTBiYTQzN2VlYTI2M2U4ZTdlZDMwMGFjZWRiMWUxODMxMDU5NjdiYjI4ZjE4ZGFlOTBmNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9HgEtaCd7ex6qco4F2qXqVkxLuehi0gh0FYI8PQ5VLg)

@sohams98 You can check the console log if facing the same issue. if yes, this issue has been fixed in v9.3.0 and above. but if it happened before upgrading, it needs to be fixed manually.

Here are the steps:
1. Check the console log to get the project ID, it is `prj_f55f925598a54b42b9b9d3ecdaa6b3f9` in the above case.
2. Go to `Help -> Show App Data Folder`
3. Navigate to `.\version-control\projects\{prj_xxx}`, you should see a file named `meta.json.{uuid}.tmp`
4. Delete `meta.json` and rename `meta.json.{uuid}.tmp` to `meta.json`

<img width="556" alt="image" src="https://github.com/user-attachments/assets/5ddb6969-ecbb-4895-b458-ef5e38bf5d6f">

<img width="752" alt="Screenshot 2024-10-12 at 12 29 21" src="https://github.com/user-attachments/assets/0a77dbad-1fd6-4765-8102-7454a7b9c9f3">

**Comment by CnApTaK** [comment]
@notjaywu thank you so much!

**Comment by notjaywu** [comment]
> > @gatzjames I opened the devs tool and this is what i see :
> > ![image](https://private-user-images.githubusercontent.com/84029275/302553042-0d99899d-9ca7-4240-81bc-fbd730dc4c1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MDcyNzQsIm5iZiI6MTcyODcwNjk3NCwicGF0aCI6Ii84NDAyOTI3NS8zMDI1NTMwNDItMGQ5OTg5OWQtOWNhNy00MjQwLTgxYmMtZmJkNzMwZGM0YzFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA0MjI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5MjhmOWZhZTRjZTBiYTQzN2VlYTI2M2U4ZTdlZDMwMGFjZWRiMWUxODMxMDU5NjdiYjI4ZjE4ZGFlOTBmNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9HgEtaCd7ex6qco4F2qXqVkxLuehi0gh0FYI8PQ5VLg)
> 
> @sohams98 You can check the console log if facing the same issue. if yes, this issue has been fixed in v9.3.0 and above. but if it happened before upgrading, it needs to be fixed manually.
> 
> Here are the steps:
> 
> 1. Check the console log to get the project ID, it is `prj_f55f925598a54b42b9b9d3ecdaa6b3f9` in the above case.
> 2. Go to `Help -> Show App Data Folder`
> 3. Navigate to `.\version-control\projects\{prj_xxx}`, you should see a file named `meta.json.{uuid}.tmp`
> 4. Delete `meta.json` and rename `meta.json.{uuid}.tmp` to `meta.json`
> 
> <img alt="image" width="556" src="https://private-user-images.githubusercontent.com/130019718/375925535-5ddb6969-ecbb-4895-b458-ef5e38bf5d6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3NDg3NDIsIm5iZiI6MTczMTc0ODQ0MiwicGF0aCI6Ii8xMzAwMTk3MTgvMzc1OTI1NTM1LTVkZGI2OTY5LWVjYmItNDg5NS1iNDU4LWVmNWUzOGJmNWQ2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNlQwOTE0MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YzRiZWVlYjhhYWY1ZjlmNjQ0OTc5MjBkNjU5OWI4M2EzMTQ0NzFiMjE1NTZiZDM3NWQxNjJiMmVlYTVkOWQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wPWmQcAEO5Jq2Pyet2nB71lHTuqoiC4upDtGgMtr99o"> <img alt="Screenshot 2024-10-12 at 12 29 21" width="752" src="https://private-user-images.githubusercontent.com/130019718/375925114-0a77dbad-1fd6-4765-8102-7454a7b9c9f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3NDg3NDIsIm5iZiI6MTczMTc0ODQ0MiwicGF0aCI6Ii8xMzAwMTk3MTgvMzc1OTI1MTE0LTBhNzdkYmFkLTFmZDYtNDc2NS04MTAyLTc0NTRhN2I5YzlmMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNlQwOTE0MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMDgwMTI1Y2NhYjI1YzQwMmI5NmZkYjNlZjUwNGE2NWRiMmMyNjdkNjE2NzZmZWQ3Mzg3MzA3Y2Q5MTRlODJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Hle2Qcet2rHIrJjPew2MuKmNj0VkxrtG0XllFHJTlcw">

Close this issue.
