### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by ghost** [getinsomnia/insomnia#7535]
### Expected Behavior

When I'm requested to enter a Passphrase, I expect to be logged.

### Actual Behavior

When I enter the Passphrase and click on continue, I get a response as on the screenshot: 
![image](https://github.com/Kong/insomnia/assets/148357093/edfb4e47-5c4b-4b8e-b10b-67ee75167d8f) You are successfully authenticated. You can click Launch button or manually enter the token.
I click on launch.
I'm thrown back to the login page.

### Reproduction Steps

Go to login page
Fill in the passphrase
I'm logged successfully
Click on launch button
Then I'm thrown to the login page again

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

It's the same issue even at the office and with the VPN.

### Insomnia Version

9.2.0

### What operating system are you using?

Windows

### Operating System Version

windows 10

### Installation method

download insomnia

### Last Known Working Insomnia version

9.2.0

**Comment by shrpow** [comment]
Me too.
When I try to paste the token into the input, I see `Invalid code: Failed to fetch`.

**Comment by ghost** [comment]
Nothing is functional. 
![image](https://github.com/Kong/insomnia/assets/148357093/a4df1999-20dc-4a67-8346-ba252ea8634f)

**Comment by subnetmarco** [comment]
@notjaywu @filfreire @marckong

**Comment by notjaywu** [comment]
@shrpow @Pessiun Can you share the console logs when logging in? It helps us to identify the problem. Thank you!

![image](https://github.com/Kong/insomnia/assets/130019718/b85c6829-8b01-4e88-8d58-224d639df761)

**Comment by shrpow** [comment]
<img width="362" alt="image" src="https://github.com/Kong/insomnia/assets/124259333/a4d48e5a-9884-49b1-ad3a-3552fd2aeb32">

Resolved. For some reason, it uses a proxy from the settings (which I forgot to renew). After I disabled the proxy, everything worked.

**Comment by subnetmarco** [comment]
@Pessiun are you also using a proxy?

**Comment by ghost** [comment]
Hi,
Yes, I’m using a proxy, thanks.

Best regards,

Mukindia Stella
QA Engineer
Technology - Savings, Financing & Advisory Services
Mobile: +46 (0) 707635753

**Comment by notjaywu** [comment]
@Pessiun You can disable the proxy in the Preference and log in again

<img width="1728" alt="image" src="https://github.com/Kong/insomnia/assets/130019718/080b1154-2d59-410e-ba24-7029205bf347">

**Comment by ghost** [comment]
Hi,
I’ve checked and the proxy was not checked.

Still not functional. How can I retrieve my  projects I’ve created to start using the
Local scratchpad?

***@***.***

Best regards,

Mukindia Stella
QA Engineer
Technology - Savings, Financing & Advisory Services
Mobile: +46 (0) 707635753

**Comment by notjaywu** [comment]
@Pessiun Could you share your console logs? You can find it from 

<img width="423" alt="Screenshot 2024-06-12 at 19 44 05" src="https://github.com/Kong/insomnia/assets/130019718/881904e6-087c-422f-ad71-7e58b053a6b4">

![image](https://github.com/Kong/insomnia/assets/130019718/14a3edbe-6e4f-40e7-b4a5-4f73ed565d4f)

**Comment by ghost** [comment]
***@***.***
***@***.***

Best regards,

Mukindia Stella
QA Engineer
Technology - Savings, Financing & Advisory Services
Mobile: +46 (0) 707635753

**Comment by ghost** [comment]
***@***.***

***@***.***



Best regards,

Mukindia Stella
QA Engineer
Technology - Savings, Financing & Advisory Services
Mobile: +46 (0) 707635753

**Comment by subnetmarco** [comment]
@Pessiun your last messages were not received properly, could you please comment again?

**Comment by ghost** [comment]
Hi,
Here is the console logs!
***@***.***

***@***.***


Best regards,

Mukindia Stella
QA Engineer
Technology - Savings, Financing & Advisory Services
Mobile: +46 (0) 707635753

**Comment by notjaywu** [comment]
@Pessiun The message should be blocked, I can't see your console log. Can you join our community Slack channel via https://chat.insomnia.rest?  I can DM you for more details.

**Comment by ghost** [comment]
![image](https://github.com/Kong/insomnia/assets/148357093/5a34b734-a7c6-4c0b-9d97-0206b804091a)

**Comment by Pessiun** [comment]
![image](https://github.com/Kong/insomnia/assets/148357093/08e826fa-e109-4c57-a8c4-605fde4422cd)

**Comment by notjaywu** [comment]
@Pessiun Sorry, I must delete your second image because it has a sensitive message. Can you check if the domain `api.insomnia.rest` is blocked by any security policy? The `/auth/whoami` request was not sent out for some reason.

**Comment by ghost** [comment]
That's not so good! Delete it completely.

**Comment by subnetmarco** [comment]
We are adding more information to detect when the network interface is online, but the connectivity may not be working because of proxies that are refusing the connection.

**Comment by jnaulhdl** [comment]
I'm having this same issue. Authentication through Google. "Enable Proxy" not checked. When I get to this popup:
![image](https://github.com/Kong/insomnia/assets/55109131/fe007382-03a1-4aa6-8593-2def4303228f)
Clicking "Manually enter token" does nothing, and clicking "Launch" sets focus to the app (or reopens app if closed), but doesn't continue with login. 

There is one error on the console after the app reopens:
![image](https://github.com/Kong/insomnia/assets/55109131/645fd616-c61a-45aa-b222-5b9942763d93)

After clicking on the link beside GET, it takes me to the Network tab to this line:
![image](https://github.com/Kong/insomnia/assets/55109131/9e9e2ff9-b4c3-4b37-84c0-e2a731da0590)

I hope this helps. If you need any additional information, please let me know.

**Comment by marckong** [comment]
@jnaulhdl Can you send us your email address in our slack via DM? https://getinsomnia.slack.com

**Comment by jnaulhdl** [comment]
@marckong Who do I need to start a DM with?

**Comment by marckong** [comment]
@jnaulhdl which timezone are you located in? For now you can send me a DM.

**Comment by jakubkuc** [comment]
I have the same problem for about 2 weeks. Is there any updates on that issue?

**Comment by subnetmarco** [comment]
@marckong any update on this front?

**Comment by marckong** [comment]
@jnaulhdl  please let us know when you are available to troubleshoot. I have not received a response from you.

**Comment by marckong** [comment]
@jakubkuc can you pleaes DM us which email you use for your account through the our public Slack channel? https://getinsomnia.slack.com/

**Comment by filfreire** [comment]
Hi folks, if you are still facing this issue, I would encourage you all to try my suggestion here: https://github.com/Kong/insomnia/issues/7647#issuecomment-2225807255

**Comment by notjaywu** [comment]
If you are using a system-level proxy, you have to manually set the proxy in the Preferences. Please see #7969 .

**Comment by notjaywu** [comment]
Close this issue, the App can automatically detect the system proxy with PR #7982.
